### ISSUE TITLE
Odd mappings from command line args to message structure for the token factory module. 

### ISSUE THREAD

**Issue by ewoolsey** [noria-net/noria#26]
I've noticed that noriad seems to have odd mappings from command line args to message structure for the token factory module. Here is an example that is strange:
First, here is the intended usage:
```
noriad tx tokenfactory modify-metadata [denom] [ticker-symbol] [description] [exponent] [flags]
```
Here is my command
```
noriad tx tokenfactory modify-metadata factory/noria1xd9qy35ys7jzp8a3nl334hexs5c9m8gwuylfj5/udai DAI "Noria Testnet Dai" 6 --from dev_key --gas auto --gas-prices 0.0025ucrd --gas-adjustment 1.5
```
And here is the resulting message:
```
  messages:
  - '@type': /osmosis.tokenfactory.v1beta1.MsgTokenFactorySetDenomMetadata
    metadata:
      base: factory/noria1xd9qy35ys7jzp8a3nl334hexs5c9m8gwuylfj5/udai
      denom_units:
      - aliases:
        - DAI
        denom: factory/noria1xd9qy35ys7jzp8a3nl334hexs5c9m8gwuylfj5/udai
        exponent: 0
      - aliases:
        - factory/noria1xd9qy35ys7jzp8a3nl334hexs5c9m8gwuylfj5/udai
        denom: DAI
        exponent: 6
      description: Noria Testnet Dai
      display: factory/noria1xd9qy35ys7jzp8a3nl334hexs5c9m8gwuylfj5/udai
      name: factory/noria1xd9qy35ys7jzp8a3nl334hexs5c9m8gwuylfj5/udai
      symbol: DAI
      uri: ""
      uri_hash: ""
```
The fields in the usage section don't correctly map to the message. The aliases aren't really created correctly, and the ticker and alias denom are somehow conflated? Very strange.
